from __future__ import annotations

import re
from pathlib import Path

from .invariant_breaker import InvariantBreakPlan, break_invariant_plan, load_analysis


def solidity_identifier(value: str, fallback: str = "InvariantPlan") -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]+", "_", value.strip())
    cleaned = cleaned.strip("_")
    if not cleaned:
        return fallback
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def foundry_test_name_from_invariant(invariant: str) -> str:
    lowered = invariant.lower()

    if "reward" in lowered and ("principal" in lowered or "redeemable" in lowered or "asset balance" in lowered):
        return "test_invariant_rewardClaimsDoNotDrainPrincipal"
    if "share" in lowered and ("redeem" in lowered or "asset" in lowered):
        return "test_invariant_allSharesRemainRedeemable"
    if "external" in lowered or "reentrant" in lowered or "callback" in lowered:
        return "test_invariant_externalCallsCannotExploitPartialState"
    if "actual" in lowered and "balance" in lowered:
        return "test_invariant_accountingMatchesActualAssetDeltas"

    return "test_invariant_" + solidity_identifier(invariant[:64], "customInvariant")


def _comment_block(indent: str, items: list[str]) -> str:
    if not items:
        return indent + "// - n/a"
    return "\n".join(f"{indent}// - {item}" for item in items)


def _sequence_block(sequences: list[list[str]]) -> str:
    if not sequences:
        return "        // Attack sequence 1:\n        //   1. TODO: construct a sequence that targets the invariant."

    lines: list[str] = []
    for idx, sequence in enumerate(sequences, start=1):
        lines.append(f"        // Attack sequence {idx}:")
        for step_idx, step in enumerate(sequence, start=1):
            lines.append(f"        //   {step_idx}. {step}")
    return "\n".join(lines)


def render_foundry_test_skeleton(plan: InvariantBreakPlan, contract_name: str = "GeneratedInvariantPlanTest") -> str:
    test_name = foundry_test_name_from_invariant(plan.invariant)
    contract_id = solidity_identifier(contract_name, "GeneratedInvariantPlanTest")

    return """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";

/// @notice Generated by audit-copilot from an invariant break plan.
/// @dev This is intentionally a skeleton. Wire protocol contracts, mocks, and actors manually.
contract {contract_id} is Test {{
    address internal actorA = address(0xA11CE);
    address internal actorB = address(0xB0B);
    address internal attacker = address(0xA77A);

    function setUp() public {{
        // TODO:
        // - Deploy protocol contracts.
        // - Deploy/mock assets.
        // - Fund actors.
        // - Approve tokens.
        // - Initialize protocol state.
    }}

    /// @notice Invariant under test:
    /// {invariant}
    function {test_name}() public {{
        // Likely attack classes:
{attack_classes}

        // Preconditions to construct:
{preconditions}

{sequences}

        // TODO:
        // 1. Implement the most realistic sequence above.
        // 2. Capture pre-state evidence.
        // 3. Execute attacker/victim actions.
        // 4. Assert the invariant still holds.

        // Evidence to collect:
{evidence}

        // Foundry helper/test ideas:
{ideas}

        fail("TODO: implement invariant break attempt");
    }}
}}
""".format(
        contract_id=contract_id,
        invariant=plan.invariant,
        test_name=test_name,
        attack_classes=_comment_block("        ", plan.likely_attack_classes),
        preconditions=_comment_block("        ", plan.preconditions),
        sequences=_sequence_block(plan.attack_sequences),
        evidence=_comment_block("        ", plan.evidence_to_collect),
        ideas=_comment_block("        ", plan.foundry_test_ideas),
    )


def write_foundry_plan_from_analysis(
    analysis_json: str | Path,
    invariant: str,
    out: str | Path,
    contract_name: str = "GeneratedInvariantPlanTest",
) -> Path:
    analysis = load_analysis(analysis_json)
    plan = break_invariant_plan(analysis, invariant)
    rendered = render_foundry_test_skeleton(plan, contract_name=contract_name)

    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered)
    return out_path
