from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .invariant_breaker import InvariantBreakPlan, break_invariant_plan, load_analysis


def solidity_identifier(value: str, fallback: str = "InvariantPlan") -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]+", "_", value.strip())
    cleaned = cleaned.strip("_")
    if not cleaned:
        return fallback
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def foundry_test_name_from_invariant(invariant: str) -> str:
    lowered = invariant.lower()

    if "reward" in lowered and ("principal" in lowered or "redeemable" in lowered or "asset balance" in lowered):
        return "test_invariant_rewardClaimsDoNotDrainPrincipal"
    if "share" in lowered and ("redeem" in lowered or "asset" in lowered):
        return "test_invariant_allSharesRemainRedeemable"
    if "external" in lowered or "reentrant" in lowered or "callback" in lowered:
        return "test_invariant_externalCallsCannotExploitPartialState"
    if "actual" in lowered and "balance" in lowered:
        return "test_invariant_accountingMatchesActualAssetDeltas"

    return "test_invariant_" + solidity_identifier(invariant[:64], "customInvariant")


def extract_protocol_context(analysis: dict[str, Any], invariant: str = "") -> dict[str, Any]:
    """Extract protocol wiring hints from analysis.json for generated Foundry skeletons."""
    transitions = _extract_transitions(analysis)
    invariant_text = invariant.lower()

    contracts = sorted({str(t.get("contract", "")).strip() for t in transitions if t.get("contract")})
    relevant = [_normalize_transition(t) for t in transitions if _is_relevant_transition(t, invariant_text)]

    if not relevant:
        relevant = [_normalize_transition(t) for t in transitions]

    state_terms = sorted(
        {
            term
            for t in relevant
            for term in [*t["reads"], *t["writes"]]
            if term
        }
    )

    external_calls = sorted(
        {
            call
            for t in relevant
            for call in t["external_calls"]
            if call
        }
    )

    asset_movements = sorted(
        {
            movement
            for t in relevant
            for movement in t["asset_movements"]
            if movement
        }
    )

    actors = _infer_actors(invariant_text, relevant)

    return {
        "contracts": contracts,
        "relevant_functions": relevant,
        "state_terms": state_terms,
        "external_calls": external_calls,
        "asset_movements": asset_movements,
        "actors": actors,
    }


def render_foundry_test_skeleton(
    plan: InvariantBreakPlan,
    contract_name: str = "GeneratedInvariantPlanTest",
    analysis: dict[str, Any] | None = None,
) -> str:
    test_name = foundry_test_name_from_invariant(plan.invariant)
    contract_id = solidity_identifier(contract_name, "GeneratedInvariantPlanTest")
    protocol_context = extract_protocol_context(analysis or {}, plan.invariant)

    return """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";

/// @notice Generated by audit-copilot from an invariant break plan.
/// @dev This is intentionally a skeleton. Wire protocol contracts, mocks, and actors manually.
contract {contract_id} is Test {{
{contract_placeholders}
{actor_placeholders}

    function setUp() public {{
        // TODO:
        // - Deploy protocol contracts.
        // - Deploy/mock assets.
        // - Fund actors.
        // - Approve tokens.
        // - Initialize protocol state.

{setup_todos}
    }}

    /// @notice Invariant under test:
    /// {invariant}
    function {test_name}() public {{
        // Likely attack classes:
{attack_classes}

        // Preconditions to construct:
{preconditions}

        // Relevant protocol functions to wire:
{function_todos}

        // Relevant state/accounting hints:
{state_todos}

{sequences}

        // TODO:
        // 1. Implement the most realistic sequence above.
        // 2. Capture pre-state evidence.
        // 3. Execute attacker/victim actions.
        // 4. Assert the invariant still holds.

        // Evidence to collect:
{evidence}

        // Foundry helper/test ideas:
{ideas}

        fail("TODO: implement invariant break attempt");
    }}
}}
""".format(
        contract_id=contract_id,
        contract_placeholders=_contract_placeholders(protocol_context),
        actor_placeholders=_actor_placeholders(protocol_context),
        setup_todos=_setup_todos(protocol_context),
        invariant=plan.invariant,
        test_name=test_name,
        attack_classes=_comment_block("        ", plan.likely_attack_classes),
        preconditions=_comment_block("        ", plan.preconditions),
        function_todos=_function_todos(protocol_context),
        state_todos=_state_todos(protocol_context),
        sequences=_sequence_block(plan.attack_sequences, protocol_context),
        evidence=_comment_block("        ", plan.evidence_to_collect),
        ideas=_comment_block("        ", plan.foundry_test_ideas),
    )


def write_foundry_plan_from_analysis(
    analysis_json: str | Path,
    invariant: str,
    out: str | Path,
    contract_name: str = "GeneratedInvariantPlanTest",
) -> Path:
    analysis = load_analysis(analysis_json)
    plan = break_invariant_plan(analysis, invariant)
    rendered = render_foundry_test_skeleton(plan, contract_name=contract_name, analysis=analysis)

    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered)
    return out_path


def _comment_block(indent: str, items: list[str]) -> str:
    if not items:
        return indent + "// - n/a"
    return "\n".join(f"{indent}// - {item}" for item in items)


def _sequence_block(sequences: list[list[str]], protocol_context: dict[str, Any]) -> str:
    if not sequences:
        return "        // Attack sequence 1:\n        //   1. TODO: construct a sequence that targets the invariant."

    action_hints = _action_hints(protocol_context)

    lines: list[str] = []
    for idx, sequence in enumerate(sequences, start=1):
        lines.append(f"        // Attack sequence {idx}:")
        for step_idx, step in enumerate(sequence, start=1):
            lines.append(f"        //   {step_idx}. {step}")
        if action_hints:
            lines.append("        //   Protocol call hints:")
            for hint in action_hints:
                lines.append(f"        //   - {hint}")
    return "\n".join(lines)


def _extract_transitions(analysis: dict[str, Any]) -> list[dict[str, Any]]:
    raw = analysis.get("transitions", [])
    if not isinstance(raw, list):
        return []
    return [item for item in raw if isinstance(item, dict)]


def _normalize_transition(transition: dict[str, Any]) -> dict[str, Any]:
    contract = str(transition.get("contract") or transition.get("contract_name") or "UnknownContract")
    function = str(transition.get("function") or transition.get("name") or "unknown")

    return {
        "contract": contract,
        "function": function,
        "fq_name": f"{contract}.{function}",
        "visibility": transition.get("visibility", ""),
        "modifiers": _as_str_list(transition.get("modifiers", [])),
        "reads": _as_str_list(transition.get("reads_storage", transition.get("reads", []))),
        "writes": _as_str_list(transition.get("writes_storage", transition.get("writes", []))),
        "external_calls": _as_str_list(transition.get("external_calls", [])),
        "asset_movements": _as_str_list(transition.get("asset_movements", [])),
        "auth_requirements": _as_str_list(transition.get("auth_requirements", [])),
    }


def _as_str_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    return [str(value)]


def _is_relevant_transition(transition: dict[str, Any], invariant_text: str) -> bool:
    normalized = _normalize_transition(transition)
    haystack = " ".join(
        [
            normalized["contract"],
            normalized["function"],
            " ".join(normalized["reads"]),
            " ".join(normalized["writes"]),
            " ".join(normalized["external_calls"]),
            " ".join(normalized["asset_movements"]),
        ]
    ).lower()

    if not invariant_text:
        return True

    keyword_groups = {
        "reward": ("reward", "claim", "emission", "lastclaim"),
        "share": ("share", "shares", "totalsupply", "totalshares", "deposit", "withdraw", "redeem"),
        "asset": ("asset", "balance", "transfer", "deposit", "withdraw"),
        "external": ("external", "call", "transfer", "callback", "reentrant"),
        "principal": ("asset", "share", "withdraw", "claim", "reward"),
    }

    wanted: set[str] = set()
    for trigger, keywords in keyword_groups.items():
        if trigger in invariant_text:
            wanted.update(keywords)

    if not wanted:
        return True

    return any(keyword in haystack for keyword in wanted)


def _infer_actors(invariant_text: str, functions: list[dict[str, Any]]) -> list[dict[str, str]]:
    actors = [
        {"name": "actorA", "address": "address(0xA11CE)", "role": "primary user / first mover"},
        {"name": "actorB", "address": "address(0xB0B)", "role": "victim or honest user"},
        {"name": "attacker", "address": "address(0xA77A)", "role": "attacker contract/controller"},
    ]

    if any(fn["auth_requirements"] or fn["modifiers"] for fn in functions):
        actors.append({"name": "admin", "address": "address(0xAD000)", "role": "admin / privileged role"})

    if "liquidat" in invariant_text:
        actors.append({"name": "liquidator", "address": "address(0x11Q)", "role": "liquidator"})
    if "keeper" in invariant_text:
        actors.append({"name": "keeper", "address": "address(0xBEEF)", "role": "keeper"})

    return actors


def _contract_placeholders(protocol_context: dict[str, Any]) -> str:
    contracts = protocol_context.get("contracts", [])
    if not contracts:
        return "    // TODO: declare protocol contract handles here."

    lines = ["    // Detected contracts:"]
    for contract in contracts:
        var_name = solidity_identifier(contract[0].lower() + contract[1:] if contract else "protocol", "protocol")
        lines.append(f"    // {contract} internal {var_name};")
    return "\n".join(lines)


def _actor_placeholders(protocol_context: dict[str, Any]) -> str:
    actors = protocol_context.get("actors", [])
    if not actors:
        return ""

    lines = ["", "    // Suggested actors:"]
    for actor in actors:
        lines.append(f"    address internal {actor['name']} = {actor['address']}; // {actor['role']}")
    return "\n".join(lines)


def _setup_todos(protocol_context: dict[str, Any]) -> str:
    contracts = protocol_context.get("contracts", [])
    actors = protocol_context.get("actors", [])
    functions = protocol_context.get("relevant_functions", [])

    lines: list[str] = []
    for contract in contracts:
        lines.append(f"        // TODO: deploy or attach {contract}.")
    for actor in actors:
        lines.append(f"        // TODO: fund/label {actor['name']} as {actor['role']}.")
    for fn in functions:
        if fn.get("auth_requirements") or fn.get("modifiers"):
            auth = ", ".join([*fn.get("auth_requirements", []), *fn.get("modifiers", [])])
            lines.append(f"        // TODO: configure access for {fn['fq_name']} ({auth}).")

    return "\n".join(lines) if lines else "        // TODO: add protocol-specific setup."


def _function_todos(protocol_context: dict[str, Any]) -> str:
    functions = protocol_context.get("relevant_functions", [])
    if not functions:
        return "        // - n/a"

    lines: list[str] = []
    for fn in functions:
        meta = []
        if fn.get("external_calls"):
            meta.append(f"external_calls={fn['external_calls']}")
        if fn.get("writes"):
            meta.append(f"writes={fn['writes']}")
        if fn.get("auth_requirements") or fn.get("modifiers"):
            meta.append(f"auth={fn.get('auth_requirements', []) + fn.get('modifiers', [])}")
        suffix = f" ({'; '.join(meta)})" if meta else ""
        lines.append(f"        // - TODO: wire call to {fn['fq_name']}{suffix}")
    return "\n".join(lines)


def _state_todos(protocol_context: dict[str, Any]) -> str:
    state_terms = protocol_context.get("state_terms", [])
    external_calls = protocol_context.get("external_calls", [])
    asset_movements = protocol_context.get("asset_movements", [])

    lines = []
    if state_terms:
        lines.append(f"        // - State terms: {', '.join(state_terms)}")
    if external_calls:
        lines.append(f"        // - External calls: {', '.join(external_calls)}")
    if asset_movements:
        lines.append(f"        // - Asset movements: {', '.join(asset_movements)}")

    return "\n".join(lines) if lines else "        // - n/a"


def _action_hints(protocol_context: dict[str, Any]) -> list[str]:
    functions = protocol_context.get("relevant_functions", [])
    hints: list[str] = []

    for fn in functions:
        name = fn["function"].lower()
        fq_name = fn["fq_name"]
        if fn.get("auth_requirements") or fn.get("modifiers"):
            hints.append(f"vm.prank(admin); call {fq_name}(...) only if admin setup is in-scope")
        elif "deposit" in name or "mint" in name or "stake" in name:
            hints.append(f"vm.prank(actorA); call {fq_name}(...) to create or skew position")
        elif "claim" in name or "reward" in name or "harvest" in name:
            hints.append(f"vm.prank(actorA); call {fq_name}(...) after warp/accrual")
        elif "withdraw" in name or "redeem" in name or "unstake" in name:
            hints.append(f"vm.prank(actorB); call {fq_name}(...) to verify honest exit")
        else:
            hints.append(f"call {fq_name}(...) if it mutates invariant-related state")

    return list(dict.fromkeys(hints))
